version: '2'

services:
  primary:
    image: mongo
    command: mongod --replSet rs0 --smallfiles
    ports:
      - 27017
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /data/db
      - /data/configdb
    restart: always
    networks:
      - mongonet

  secondary:
    image: mongo
    command: mongod --replSet rs0 --smallfiles
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /data/db
      - /data/configdb
    networks:
      - mongonet

networks:
  mongonet:
    driver: bridge
